### ISSUE TITLE
Error when payment not received

### ISSUE THREAD

**Issue by bblaha** [brainblocks/brainblocks#10]
Right now the network seems to be a bit congested, so I only get half of the payments through.
However, when one does not go through I get these errors:
`Uncaught (in promise) Error: Api /api/session status: error
    at button?version=latest&logLevel=warn&env=production&uid=394a288308&xcomponent=1:125
    at <anonymous>
button?version=latest&logLevel=warn&env=production&uid=394a288308&xcomponent=1:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
button?version=latest&logLevel=warn&env=production&uid=394a288308&xcomponent=1:166 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at openButton (button?version=latest&logLevel=warn&env=production&uid=394a288308&xcomponent=1:166)
    at HTMLDivElement.<anonymous> (button?version=latest&logLevel=warn&env=production&uid=394a288308&xcomponent=1:242)`

I have to reload the page to be able to initiate a new payment.

**Comment by bluepnume** [comment]
Thanks for the report! I'll look into this -- ideally you shouldn't have to refresh the page.
