### ISSUE TITLE
Payment not received by pexpeppers?

### ISSUE THREAD

**Issue by vschwanke** [brainblocks/brainblocks#12]
Hi there, I used brainblocks to pay for some hot sauce, and the withdrawal went through on my end but pexpeppers never received payment and the order never confirmed. I sent 1 raiblock for sauce that cost like $16. I contacted them and they told me to contact you. Any advice? Thanks!

Address:
xrb_3ydu3y8soipe581hpyebrmubg7rprie5ijzedkh1seiccr4p59d1jdcbtb5a

Transaction ID/block:
AA2A2784161CF9D023ABB8CB3F7BD9EEC0D600CB9BE4CE3F5EE5B5B636D8BED0

**Comment by bluepnume** [comment]
Hi -- thanks for the heads-up. Can you let me know which wallet you sent the raiblocks from? Or was it your local wallet, and if so was it in-sync with the network?

Whatever happens I'll get a refund your way, for sure. But I'd like to understand the issue so I can make sure we have the right safeguards on our side. Thanks!

**Comment by vschwanke** [comment]
Thanks. It's likely my fault because I sent it straight from my bitgrail account.

**Comment by bluepnume** [comment]
OK, thanks for letting me know. Can you let me know the address to refund you?

**Comment by vschwanke** [comment]
Thanks so much. This time I'll try the transaction using my raiwallet. Thanks.

xrb_3fz5wfnkn1sndysw6ahqc7odjoztnx5j79woxpdhowonfxoranab376j3r5d

**Comment by bluepnume** [comment]
OK, thanks - the refund should be made.
