### ISSUE TITLE
Update CORS settings to allow cross origin calls from front end apps

### ISSUE THREAD

**Issue by goldcaddy77** [brainblocks/brainblocks#13]
Hi, I'm getting the following error while trying to do verification in my React app:

> Failed to load https://brainblocks.io/api/session/<token>/verify: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:6006' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Thoughts on making the CORS settings less strict?

**Comment by bluepnume** [comment]
Verify should only really be called from the server side. The idea is it's to prevent malicious parties spoofing a transaction or altering the amount on the client side. So your server should make this call and check everything matches up.

**Comment by goldcaddy77** [comment]
So assuming I'm a merchant selling things, the process would be:

- Page creates a button with correct address and amount
- User pays with button
- Client button `onPayment`sends transaction ID to merchants APIs
- Merchant calls ` https://brainblocks.io/api/session/_token_/verify`to make sure things happened as expected?

Two things:

1. What happens if client experiences an error and the token is never posted to the server?
2. Would there be no reason for client-side code to ever want to do this verification or get access to anything returned in the verification payload?

**Comment by bluepnume** [comment]
1. Right now it's up to the vendor's site to retry if there's a network error. Open to suggestions here.

2. No -- any info the client needs should be passed back in `onPayment()`. If there's anything missing here I can add it in.

**Comment by goldcaddy77** [comment]
1. Perhaps you could allow a callback URL where you’d post the ‘onPayment’ and transaction details, too, so that the server isn’t reliant on the client making it aware of the transaction.

2. Oh gotcha, so the verify URL is really just a means for an application to look up transactions after the fact. Not sure what you’d pass through but I thought you just pass success and token through now.

**Comment by goldcaddy77** [comment]
@bluepnume - how is the server letting you know that the payment was successful?  I didn't see a socket open and there is no polling.  Is it magic? :)

The `/verify` URL would be great for this - could poll every few seconds

**Comment by bluepnume** [comment]
There's a long-poll ajax call from the client :)

<img width="581" alt="screen shot 2018-01-28 at 4 14 49 pm" src="https://user-images.githubusercontent.com/1219075/35489047-664b66b8-0446-11e8-9017-ab0c3872a94b.png">

That said -- this isn't a public api, so wouldn't recommend calling it from your own back-end, in case something breaks in future when it changes.
