### ISSUE TITLE
Error with NPM package install

### ISSUE THREAD

**Issue by goldcaddy77** [brainblocks/brainblocks#14]
Hey, when I try to install the npm package for consumption in my project I get:

```
yarn add brainblocks
...
...
error <path>/node_modules/brainblocks: Command failed.
Exit code: 127
Command: flow-typed install
Arguments:

```

Do you actually need to run `flow-typed install` in the `postinstall` script?

**Comment by bluepnume** [comment]
Yep, good call. I've removed this and published a new version.
