### ISSUE TITLE
Circular spinner visible before clicking button

### ISSUE THREAD

**Issue by Lorenzo45** [brainblocks/brainblocks#16]
I’ve checked out the BrainBlocks button a few times on iOS using the Safari browser and every time I do, I see a weird visual glitch where the spinner is visible (usually over other content) before I click on the button. Just wanted to make sure you were aware of this!

**Comment by Lorenzo45** [comment]
Here’s a screenshot of what I see: https://ibb.co/hWnC9G

**Comment by bluepnume** [comment]
This should be fixed, please let me know if you still see the problem
