### ISSUE TITLE
Customer stipulates transfer amount by entering Fiat equivalent

### ISSUE THREAD

**Issue by ppeach** [brainblocks/brainblocks#17]
It would be great if the customer was able to input the transfer amount in their local fiat and then have this converted to an XRB amount at the time of transfer.

**Comment by bluepnume** [comment]
The only problem with this would be, how would you verify the right amount was sent before you confirm the transaction on your server?

**Comment by ppeach** [comment]
Pull the current exchange rate off the coinmarketcap API to convert their fiat input into an XRB amount and handle that XRB variable in the payment and verification
