### ISSUE TITLE
React Native Integration

### ISSUE THREAD

**Issue by brianfoody** [brainblocks/brainblocks#20]
Hi all,

Not so much an issue as feature request which I am happy to do myself. I would like to integrate RaiBlocks payments into my React Native app. Any pointers would be helpful. 

As this renders to a HTML element I'm guessing I can just create a React Native element that renders instead and reuse the JavaScript logic?

For the owners of the repo, would you like me to fork this repo and create a brainblocks-react-native?

Cheers,
Brian

**Comment by bluepnume** [comment]
Paging @schenkty -- he built https://github.com/brainblocks/brainblocks-ios-sdk -- I would hope this should be pretty easy to drop into react native.

**Comment by schenkty** [comment]
Hey @brianfoody, take a look here: [Linking libraries](https://facebook.github.io/react-native/docs/linking-libraries-ios.html). Also, I do not maintain this so I can not provide any support but somebody made: [ReBlocks](https://github.com/goldcaddy77/reblocks). Let me know if neither of these work.

**Comment by bluepnume** [comment]
FWIW, I'm suspecting the first approach may be better, since the latter just wraps the web component.

**Comment by schenkty** [comment]
I agree the first option may be best.

**Comment by brianfoody** [comment]
Thanks all. Was planning on going with option a which is easy peasy but the pod spec is limited to iOS 11 which rules it out for any existing projects really. Ideally I'd like this to be available to at least iOS 10 to improve adoption.

**Comment by schenkty** [comment]
Let me look into updating that. There were a few things that required 11.0 but I may be able to just update them with 10.0 support.

**Comment by brianfoody** [comment]
That would be great @schenkty of possible, appreciate it. 

I can get a quick version out that supports React Native on iOS and then build an Android component after.

**Comment by schenkty** [comment]
Just updated the SDK with iOS 10.0 support. [v0.0.6](https://github.com/brainblocks/brainblocks-ios-sdk/releases/tag/v0.0.6)

**Comment by yleflour** [comment]
Hello all,

I just started implementing a React Native library (pure JS). I managed to create a brainblock session. Next step is displaying + QRCode. Then I will handle the payment success callback.

**Comment by brianfoody** [comment]
Hi @yleflour. Sorry I should have updated this ticket. I built a pure JS version yesterday which I've just deployed today as I wanted Android support as well. Happy to collaborate if you want?

https://www.npmjs.com/package/react-native-brainblocks

I'm looking to add the payment option to my app later this week and hopefully generate a real world sale using this technology :-)

https://itunes.apple.com/au/app/home-addict/id1249790712?mt=8

**Comment by schenkty** [comment]
Hey, @brianfoody I tried to download your app to check it out but it is not available in the US. is there any way you can fix that? I would love to check it out

**Comment by brianfoody** [comment]
Hi @schenkty. I can't release in US just yet in case someone downloads and orders as only have Australian shipping sorted. 

If you drop me an email to brian@homeaddict.co I can add you to TestFlight if that suits? Should have RN Brainblocks integration competed by end of today.

**Comment by schenkty** [comment]
TestFlight works great. I'll email you

**Comment by brianfoody** [comment]
Pretty much feature complete on this. Completed fiat currency conversion and added an autoplay property. For my use case I wanted to navigate to a screen where the payment started automatically so it made sense to include.

https://github.com/brianfoody/react-native-brainblocks
https://www.npmjs.com/package/react-native-brainblocks

**Comment by bluepnume** [comment]
@brianfoody -- nice work man! This is looking fantastic.

Let me know if you'd like a repo under github.com/brainblocks for this -- and don't forget to post your work on reddit when you're ready.

**Comment by brianfoody** [comment]
Cheers @bluepnume, pretty handy building on top of what you've done.

I have posted to reddit now. Okay I might as well put it under github.com/brainblocks to help other devs out. Thanks.

https://www.reddit.com/r/RaiBlocks/comments/7tzd46/react_native_brainblocks_library/
