### ISSUE TITLE
Transferring less than 1 rai gets instantly verified

### ISSUE THREAD

**Issue by alexmok** [brainblocks/brainblocks#24]
I'm working on an Android SDK for brainblocks and encountered an issue. 

If the amount of rai transferred is < 1, Brainblocks rounds down and treats it as 0, so the transaction is completed immediately (without payment). I was testing the app using 0.001XRB transfer, so it automatically went through each time. If I set the amount to be >= 1, then it works as intended.

Ty just told me that 1 rai = 0.000001XRB, so I shouldn't have been entering the amount as 0.001. I had originally thought it was in XRB, so I put in 0.001 in the amount to transfer for that session. Here's how it looks if the amount of rai for the transaction is set to < 1. https://imgur.com/a/RdDXM

If Brainblocks does not intend to support transactions of less than 1 rai, I feel like it should return an error if the user tries to pay less than that instead of having the transactions instantly go through without payment.

**Comment by schenkty** [comment]
hey check your pm on Reddit :)

**Comment by bluepnume** [comment]
Hey, this is a good catch. I've added a validation error for anything < 1 rai. Thanks for letting us know!
