### ISSUE TITLE
how to check if token id is unique?

### ISSUE THREAD

**Issue by tkek55** [brainblocks/brainblocks#25]
so i can verify the amount, currency, destination etc but how do i make sure that the token is uniqe? do i need store it in a database?

**Comment by bluepnume** [comment]
Right now the recommendation would be to persist this in your db. In the longer term we'll provide an api to mark the transaction as 'complete' so you don't have to persist this yourself.

**Comment by tkek55** [comment]
amazing thanks! implemented brainblocks into my site and works like a charm!
