### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by yleflour** [brainblocks/brainblocks#26]
Hello, I am a React-Native developer and would like to contribute by implementing React-Native payment components for RaiBlock using BrainBlock.

I am trying to avoid using the Native SDK as it is much simpler for RN devs to use pure RN components.

My only issue is that after going through your repos I don't understand at all how your library works and which API to call.

So I would gladly like to get some pointers telling me where to start.

Thank you 😄

**Comment by yleflour** [comment]
Quick update, just looked at the iOS Swift implementation. API usage is now much clearer to me but it wasn't easy getting all the infos.

**Comment by bluepnume** [comment]
Hi! Did you take a look at this thread? https://github.com/brainblocks/brainblocks/issues/20

**Comment by yleflour** [comment]
@bluepnume Just saw the update. I'll be contributing to this repo from now on. API documentation would still be great though.
