### ISSUE TITLE
Bigger QR code + Pay string

### ISSUE THREAD

**Issue by sciedou** [brainblocks/brainblocks#31]
Hi there,
Is there any way to make the QR code bigger? Doing some tests, my iPhone 6+ camera don't recognize the qr code as I believe it is too small.

Also: I don't really like the word "Pay" in the button, can I change it to "Send" in some way?

**Comment by Vindexus** [comment]
>Also: I don't really like the word "Pay" in the button, can I change it to "Send" in some way?

This seems pretty doable, I might take a crack at it.

**Comment by sciedou** [comment]
> This seems pretty doable
Yeah, I tried changing it with jQuery "window on load" and "document ready", by getting the span class"pay-text" but it doesnt work.

**Comment by elronalds** [comment]
It looks like the QR code is an inline base64 data image of content type image/gif.  Would it be better to switch this to an SVG QR code so it can be scaled responsively with some simple CSS?

**Comment by sciedou** [comment]
> switch this to an SVG

or just use the google qr apis - they are deprecated but do work...

**Comment by elronalds** [comment]
I think the SVG is best.  Google API's are blocked in places like China so we'd want to ensure they can adopt this for payments.

**Comment by takitus** [comment]
SVG would be much better. I was also unable to use the current QR code with the nano beta iOS app. This should definitely be checked when updating implemention..

**Comment by bluepnume** [comment]
We're using a larger svg based QR code now. Can you please let me know if you still see any issues?

**Comment by schenkty** [comment]
There has not been any update on this. Please open again if needed.
