### ISSUE TITLE
QR Code doesnt work in iOS App

### ISSUE THREAD

**Issue by takitus** [brainblocks/brainblocks#35]
I was unable to use the QR code in the iOS App. Might be the wrong format. 

Rendering it in SVG could help too, as enlarging it makes it blur

**Comment by schenkty** [comment]
Hey @takitus, is the issue on the SDK or the App? Please keep in mind that the app is not finished and many parts are broken.
Thanks,
Ty

**Comment by schenkty** [comment]
Hey also if you can provide more detail regarding the rendering of the QR code - what is being enlarged. That would help. Thanks

**Comment by caseyscarborough** [comment]
Hi @schenkty, I'm seeing this issue as well. The scan works from nanode and the RaiBlocks explorers. Decoding the QR code from those sites results in just the XRB address, whereas decoding the brainblocks QR code results in the address prefixed with `xrb:`, i.e. `xrb:xrb_1uar8cztkufezcoy956wynh3utbpmebdeoib679zjj8bohyagykamfe3agsk`.

I believe removing the `xrb:` prefix would resolve the issue.

**Comment by schenkty** [comment]
Thanks @caseyscarborough @takitus. The `xrb:` prefix was to support the QR standard for nano. It appears that is not needed. I will push an update out with the fix

**Comment by schenkty** [comment]
@caseyscarborough @takitus please use SDK v0.0.13

**Comment by caseyscarborough** [comment]
@schenkty The QR code on the main site at https://brainblocks.io has the issue as well. The new Nano iOS wallet won't scan that one.
