### ISSUE TITLE
Installing brainblocks on zencart

### ISSUE THREAD

**Issue by ExtraSynaptic** [brainblocks/brainblocks#38]
ZenCart is one of the easiest carts to configure and modify, so it shouldn't be too difficult, I just am very naive when it comes to PHP. What exactly do I need to do to get this to work?

The first step on brainblocks.io is this: https://i.imgur.com/gW52OF2.png

Does it matter where I paste this code? Do I make a new file or add this to a certain page that handles the checkout process? What type of file should be used? Do I need to change the address listed to my own nano wallet? Are the numbers listed (1000 rai) static or is this an example? I am hoping to have my cart come up with the cost based on the USD or other currency conversion to XRB.

For the second part (https://i.imgur.com/Gnmfbfm.png), I may as well be reading greek, how and what would I need to do in order to call the brainblocks api? Do I change any of the content? What type of file needs to be created, or where does this code need to be placed?

I also found this (https://www.reddit.com/r/RaiBlocks/comments/7tj08i/can_someone_explain_me_how_to_verify_transaction/), which seemed to clarify some details, but I must have done it incorrectly as I did not see a nano checkout button when the following files were made. I assume I did something wrong, I am not a programmer and am lucky enough to be able to copy and paste code at times, let alone something like this.

Any and all help would be appreciated, and I do think this information can help other shop owners, which will cause an exponential growth type event once other businesses realize what their competition has on their hands.

Thank you!

**Comment by bluepnume** [comment]
Hi! Sorry for the late response, we've been focusing on a lot of other things. I'll try to answer some of your questions:

> Does it matter where I paste this code?

The code needs to be run anywhere on the page where you want to display the button.

> Do I make a new file or add this to a certain page that handles the checkout process?

I'm not totally familiar with Zen Cart, but I suspect it would need to be shown on an existing page.

> What type of file should be used?

So long as this code is run on the client side, you can put it in an html file or a php file, or anything else that renders html to the browser.

> Do I need to change the address listed to my own nano wallet?

You'd need to put the receiving address in the `destination` field, yes.

> Are the numbers listed (1000 rai) static or is this an example? I am hoping to have my cart come up with the cost based on the USD or other currency conversion to XRB.

You can pass `{ currency: 'usd', amount: '19.99' }` and pass whatever amount you like.
