### ISSUE TITLE
Failed to load 'try' button

### ISSUE THREAD

**Issue by GarryBullock** [brainblocks/brainblocks#39]
![screenshot](https://user-images.githubusercontent.com/14207857/36292236-4e1066ac-128d-11e8-86d3-c66a9cef68ca.PNG)

![screenshot_2](https://user-images.githubusercontent.com/14207857/36292237-525b08ac-128d-11e8-86ad-ab783a0642b5.PNG)

Failed to load the try it button on brainblocks.io. Nothing else unusual on the website.

Browser: Chrome 63.0.3239.132
OS: Windows 10 Version 1709 (Build 16299.248)

I was able to reproduce by sending payment through, waiting for completion, and then opening the try button again.

**Comment by bluepnume** [comment]
Thanks for the issue -- I'll take a look and get this squared away.

**Comment by schenkty** [comment]
This was fixed.
