### ISSUE TITLE
max amount 5 XRB?

### ISSUE THREAD

**Issue by joeblack33** [brainblocks/brainblocks#4]
is this just me or known issue?
cant input amount higher than 5 XRB (5000 rai) or else script refuses to run/appear

**Comment by bluepnume** [comment]
Hi! Yeah this is a limit I put in during the pilot phase, but I'll be happy to increase it soon as the app becomes stable.

**Comment by joeblack33** [comment]
awesome thank you for the fast response!

**Comment by bluepnume** [comment]
This is now lifted.
