### ISSUE TITLE
Support of other cryptocurrencies (like Stellar Lumens)

### ISSUE THREAD

**Issue by tipa** [brainblocks/brainblocks#43]
Would it be possible to expand the functionality of Brainblocks to accept other currencies or will the project stick to Nano payments only? Obviously, only cryptocurrencies with a fast transaction time (a few seconds) could be considered to give quick feedback during the checkout process - Stellar Lumens would be one of them.
As Stellar transactions contain a fee, this would possibly have impacts on the whole checkout process. To cover the additional transaction costs (to forward money to the destination address & refunds to source address), you could charge a larger fee for the initial Brainblocks transaction (3-4x the Stellar fee) which then can be used to cover the following fees (if needed). If the fees are not needed to the full extent (e.g. no refund) you could use them to cover the server costs.

**Comment by bluepnume** [comment]
We'll definitely consider this, but right now our full focus is on delivering the best possible experience with Nano. Also, some of the features of BrainBlocks depend on the transaction being free -- like us being able to auto-refund any amount paid over the total.
