### ISSUE TITLE
Getting Errors

### ISSUE THREAD

**Issue by JordanCoder** [brainblocks/brainblocks#46]
I tried testing out the button and sent 0.001 nano to the address and then waited for about a minute or two. I don't know what's supposed to happen when the payment is received, but for me the button just went back to its original state and errors showed up in the console:

<img width="1280" alt="screen shot 2018-02-28 at 5 13 33 pm" src="https://user-images.githubusercontent.com/25901178/36818504-ef7a3bd6-1caa-11e8-93b7-b075b232401e.png">

I'm very new to nano and using crypto wallets in general so it's possible that I could be doing something wrong too.

**Comment by bluepnume** [comment]
Can you share the address you sent the nano to?

**Comment by JordanCoder** [comment]
I've tried it multiple times and gotten the same results. Here's one of the addresses that was generated by Brainblocks for me to send the nano to: 

xrb_3wg7x4d1wwrd7hdd46uuxq888bhfn7tu4ytr98fhh43uwnmkwxto3njjbk7a

If you look it up on a block explorer like nanode it shows that the 0.001 nano is pending and says that the account is not opened yet.

**Comment by bluepnume** [comment]
I think we're out of the woods now. I've manually kicked off a refund for `xrb_3wg7x4d1wwrd7hdd46uuxq888bhfn7tu4ytr98fhh43uwnmkwxto3njjbk7a` -- please let me know if you have any more accounts where the payment is stuck in limbo and I'll kick off a refund.

**Comment by JordanCoder** [comment]
Thanks, but they were just penny transactions to test it so don't bother. :) I'm glad it's working now!
