### ISSUE TITLE
brainblocks.io appears to be down

### ISSUE THREAD

**Issue by Shogan** [brainblocks/brainblocks#47]
Not an ideal place to raise this issue here, and I'm sure it's probably been noticed, but thought it would be good to add the issue so that we can get some insight into what might be the problem.

I noticed the brainblocks icon on my app not appearing, so after quick investigation I noticed the main site is down.

Any ideas what the problem is? Expected or unexpected hosting issues?

**Comment by JordanCoder** [comment]
It sounds like expected downtime that is taking an unexpectedly large amount of time:

https://www.reddit.com/r/nanocurrency/comments/8132fp/brainblocks_temporarily_down/

**Comment by bluepnume** [comment]
Closing this as we've gotten our servers to a fairly stable place now, without any recent downtime. Thanks so much for reporting this.
