### ISSUE TITLE
Use the custom URI protocol on clicking

### ISSUE THREAD

**Issue by guilhermelawless** [brainblocks/brainblocks#5]
Adding this feature would make **brainblocks** ready for more desktop wallets as well. In my opinion, confirmation should be done on the wallet side.

Who knows, maybe something like gnome-gmail will appear that redirects to the web wallet to do the same, or even a browser extension (scary to use, but exists already).

I am in love with the project, by the way. Thank you!

**Comment by bluepnume** [comment]
Sounds like a good plan 👍
