### ISSUE TITLE
Include braiblocks in Prestashop.

### ISSUE THREAD

**Issue by andrzpj** [brainblocks/brainblocks#50]
Hello team.

Best regards, my name Andrews Pernía @ Nano26 t.me/Nano26, manager of the official Nano community in Spanish @ NanoEs t.me/NanoEs. I am currently creating an online store for Bitmain products and would like to add their gateway to receive payments in Nano.

I would like to know what the procedure is and how I can help you to carry out this project.

Greetings.

**Comment by bluepnume** [comment]
Hi! We're currently researching PrestaShop integrations. If you have any luck with this, please let me know.
