### ISSUE TITLE
Brainblocks Javascript errors after 100 seconds

### ISSUE THREAD

**Issue by ajettel** [brainblocks/brainblocks#52]
Leaving the payment prompt open for ~100 seconds results in javascript errors that make the QR and XRB address disappear. To fix it a page refresh is required. Able to reproduce on main site and personal site.

**Comment by bluepnume** [comment]
Thanks for the report. Looking into it.

**Comment by bluepnume** [comment]
Fixed for now. Looks like cloudflare was timing us out after 100 seconds. :( 

https://support.cloudflare.com/hc/en-us/articles/200171926-Error-524-A-timeout-occurred
