### ISSUE TITLE
Problem with opencart extension 

### ISSUE THREAD

**Issue by uzitotte** [brainblocks/brainblocks#57]
Hello there!

I have a problem with the extension for opencart and would be super happy if there is a solution for this!

First problem is that it creates a two payment buttons instead of one

Then also the plugin is align to the right and not the left!

I think it will be self explanatory if you view the attached screenshot

Thanks!

![screen shot 2018-03-14 at 01 34 54](https://user-images.githubusercontent.com/37353522/37377117-6eb25c26-2728-11e8-9259-7928bf55bedf.png)

my site URL is http://bersau.se

**Comment by davidteal** [comment]
Hi @uzitotte.

I wrote the OpenCart plugin so I'll try to help here. I just tried to checkout on your site and the button only appeared once. Are you still having this double button issue?

If you want to align the plugin to the left, you will need to make a small amendment to the template file. Edit catalog/view/theme/default/template/extension/payment/brainblocks.twig and on the top line change `pull-right` to `pull-left`. That's it!

If you have any more problems with the OpenCart plugin, please raise a bug report on the OpenCart specific Github page: https://github.com/brainblocks/brainblocks-opencart

Thanks.

**Comment by schenkty** [comment]
Closing since this appears to be solved.
