### ISSUE TITLE
Is there a way to use BrainBlocks as an API?

### ISSUE THREAD

**Issue by ThalesH7** [brainblocks/brainblocks#58]
Hey there,

Is there a way to use BrainBlocks as an API? I want to use BrainBlocks but I don't want to use the button rendered by it. I want to use a button that already exists in my website.

When this button is clicked, I want to se create a new transaction (receive wallet and the amount the customer needs to send). After that, I want to keep track of how the transaction goes (maybe a cronjob) and when it is confirmed, update my database and send the user an e-mail. All this must be done serverside and not in a JavaScript code.

**Comment by schenkty** [comment]
There is not a BrainBlocks API for public use. If you need to contact me, my email is ty@brainblocks.io . Thanks, Ty
