### ISSUE TITLE
Missing transaction

### ISSUE THREAD

**Issue by kilrizzy** [brainblocks/brainblocks#59]
While testing a transaction I sent to the listed address and the timer never caught it and it never seemed to pay out. Not sure if there's anything that can be seen from the explorer?

https://nano.org/en/explore/block/1FD2104B8C0F88562921B760BA71BC9A9A87BFF4F3A8BA549F7C5AA1955CD24B

**Comment by bluepnume** [comment]
Hi, looks like this one didn't make it through in time and was auto-refunded.

**Comment by kilrizzy** [comment]
Ah, thanks!
