### ISSUE TITLE
Google search for "brainblocks" shows poor results

### ISSUE THREAD

**Issue by AyiSoli** [brainblocks/brainblocks#60]
Hey guys, A google search shows the html code, I believe the page is not formatted for search engines

See the example below:  

![screen shot 2018-03-22 at 8 27 59 pm](https://user-images.githubusercontent.com/29357634/37778343-b51da024-2e0f-11e8-947e-bbac5666e68d.png)

**Comment by schenkty** [comment]
Thank you. I will look into this.

**Comment by schenkty** [comment]
fixed
