### ISSUE TITLE
Support for Splitting Payment by Percentage

### ISSUE THREAD

**Issue by DeedleFake** [brainblocks/brainblocks#61]
I've been tossing around an idea involving users of a service paying other users and the service getting a small percentage of every purchase. brainblocks could vastly simplify things, but it doesn't appear at the moment to have the ability to direct payments to multiple accounts. Would it be possible to add the ability to specify percentages of a payment to go to multiple accounts?

For example:

```javascript
brainblocks.Button.render({
    payment: {
        destination: [
            {account: "<service's address>", percentage: 5},
            {account: "<end-user's address>", percentage: null}, // For remaining.
        ],
        currency: 'rai',
        amount: 10000,
    },

    onPayment,
}, '#nano-button')
```

I don't know how feasible this is, but if it's possible it could be quite useful.

**Comment by schenkty** [comment]
This is a very interesting idea, I will look into it. Thank you
