### ISSUE TITLE
Stucked balance

### ISSUE THREAD

**Issue by viniciusfrias** [brainblocks/brainblocks#65]
Hi,

I gotta a transaction stucked since April 27, i.e. the client sent but it never hit in my wallet. Here is the ID: https://www.nanode.co/account/xrb_18r1j81zxw7x54k77tug6ax9znpzhmqpsh49towu3kfkts9kffrxzgkcysqu

The last time I faced this issue after a couple days eventually it was refunded, but i'm concerned why it happened again and if there is anything I can do to 'unstuck' the balance?

Thanks in advance,

Vinicius

**Comment by bluepnume** [comment]
I've kicked off a manual refund to your account.
