### ISSUE TITLE
incorrect amount

### ISSUE THREAD

**Issue by baronjpetor** [brainblocks/brainblocks#68]
Hi,
One of my customers made a payment by Nano today directly from his binance account. He made a mistake and sent me 29.99 instead of 29.89 Nanos and the payment wasn't reforwarded to my wallet.

These are the transaction info:

txid: C5ADE9B4E6409552BD61C64B44BFC03638898A846B6226D01BF79E1A3135FD08

address: xrb_19kdb89yx8b99spxazg9bqj3kfj7zpmndrm7k3wemqtg4o5r464ouu5jcru

my NANO address (set up on my e-commerce cuerpoymente.mx is xrb_3xdpyfanhcocten85r59e7zh1nytwtn68s317urdfgcc5on1iqqi8wusju18 )

Do you think you can help me please?

Thanks,

Max

**Comment by schenkty** [comment]
This transaction was refunded not processed and it is no longer in our system. Payments can always be overpaid and any remaining balance will be refunded back to the sender. Please have them pay you again.
