### ISSUE TITLE
Payment from Binance not fast enough

### ISSUE THREAD

**Issue by freerkjelsma** [brainblocks/brainblocks#69]
Hi,

I recently had two customers that did try to pay with Nano by sending directly from Binance:
https://www.nanode.co/account/xrb_3t8zu7ap9ad55ziff1ic9bfcdegqj4abyywihmgk4mzipfg4owefw8ss9zsh
https://www.nanode.co/account/xrb_1zdhjz39c9b76tru58iiaeunqm65poetph3nxmj194uj5nhthp5oj1snkbzn

I guess in both situations Binance didn't process them fast enough as it seems their Nano is returned.
Is there are possibility to increase the timeout?

I haven't had any response yet from the 2nd customer, but the 1st customer claims the Nano didn't show up in his Binance account, even after two days he didn't receive them back.
Isn't it possible to forward the Nano to the requested wallet, even if it timed out - or wrong amount?
The merchant can then decide to do the refund or process the payment manually (as the onPayment callback didn't execute).

Edit: another customer, same issue:
https://www.nanode.co/account/xrb_3s11c7434c8s51rn3id9ohmyowshm671ett48b5eopr6s6ik38n78u8z7qoh

Edit 2: the 2nd customer also replied Binance didn't add the Nano back into his account.

**Comment by freerkjelsma** [comment]
Any update?
I've already got two more customers with this issue.. its kinda bad Binance doesn't add the balance to their account again. Now both the customer and myself got nothing.

**Comment by enodr** [comment]
Deposit addresses and withdrawal addresses are two different things. If you pay directly from you binance account, the Nana are sent from an address which is not your deposite address. Thus, refunds cannot be automatically added to your balance on binance. I think there is not much that can be done. Only advice is: NEVER pay from an exchange account, use a proper wallet.
