### ISSUE TITLE
Shopify changes

### ISSUE THREAD

**Issue by romainjj** [brainblocks/brainblocks#70]
I saw you made changes on your website but since this, I don't get any payments on my wallet. Even though the API says it's successfully paid. Nano wallet : xrb_3tjdpnfi8bg3gy99cc4x8msemjn9ubz7rkwidfdeiju8c1doc7xysyzoeuxp

The amount in question is: 1.307

**Comment by schenkty** [comment]
Can you provide me any more details on this transaction?
