### ISSUE TITLE
Uncaught ReferenceError when using self hosted Brainblocks file

### ISSUE THREAD

**Issue by Mitcheljager** [brainblocks/brainblocks#71]
`Uncaught ReferenceError: __POST_ROBOT__ is not defined` 

I am getting a Javascript error when using a self hosted Brainblocks JS file. 

- It does not happen with the hosted file. 
- It did not happen before 1.0.8
- I am using the non-minified version. I am not certain if it makes a difference.

**Comment by bluepnume** [comment]
Yikes, good catch. I've pushed a fix. Can you try with `1.0.9`? Thanks for the report!

**Comment by Mitcheljager** [comment]
@bluepnume It has been fixed! Thanks for the quick work.
