### ISSUE TITLE
Payment Button Failing With Error

### ISSUE THREAD

**Issue by epichi123** [brainblocks/brainblocks#72]
I've tried using the payment button on both a live website and in a local html file. In both cases I got the following popup error after about 20 seconds of waiting: There was a problem processing your payment. Any nano sent will be automatically refunded. Please try again

**Comment by bluepnume** [comment]
Do you see the same problem using the example button at https://brainblocks.io?

**Comment by epichi123** [comment]
Yep, I tried it with the example button and I get the same error

**Comment by epichi123** [comment]
Ok I figured it out. Basically brainblocks and my vpn weren't playing nice with each other
