### ISSUE TITLE
Can not access my NANO Wallet

### ISSUE THREAD

**Issue by MateusLPG** [brainblocks/brainblocks#77]
Good night.
I am having some troubles while trying to access my NANO Wallet. I had to send my smartphone to the techinical assistance but before that I removed the 2 FA from my account and today when I was trying to access my account it keeps asking me the authenticator code but it was not supposed to be asking. Could you help me?

**Comment by schenkty** [comment]
Hey @MateusLPG, please contact support@nanowallet.io. 

Thanks, 
Ty
