### ISSUE TITLE
Could you please support COP? :)

### ISSUE THREAD

**Issue by lauramartinez** [brainblocks/brainblocks#8]
I'm planning on using this AMAZING payment gateway very soon on my site!
Thank you so much for being awesome!

**Comment by bluepnume** [comment]
Can you link me to COP?

**Comment by lauramartinez** [comment]
Apologies. I probably should've been more specific. I meant COP as in Colombian Peso: https://en.wikipedia.org/wiki/Colombian_peso

**Comment by schenkty** [comment]
we now support COP
