### ISSUE TITLE
orders don't show up after being paid with brainblocks 

### ISSUE THREAD

**Issue by peteblank** [brainblocks/brainblocks#82]
I got many errors on my error log but this one stood out as being related to brainblocks. 
`Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'brainblocks_token_query' not found or invalid function name in /home/u598547570/domains/nanoid.store/public_html/wp-includes/class-wp-hook.php on line 286`

**Comment by schenkty** [comment]
We are looking into this issue. Thank you!
