### ISSUE TITLE
nanowallet.io - can't send, can't pocket, balance wrong, etc

### ISSUE THREAD

**Issue by lgvz** [brainblocks/brainblocks#83]
* I have some money on nanowallet.io and sending does not work. It says the block was built succesfully, the thing appears under "pending blocks" and then nothing, no matter how long I wait. After logging out and in there is no trace of the send at all, not even in the debug logger.
* There is also one pending receive that just never gets pocketed.
* Balance randomly shows correct or some other amount
* Pending amount is *always* zero.

I want to be able to send ASAP.

Firefox 68.0.1 (64-bit) on Linux

**Comment by schenkty** [comment]
We have resolved issues with nanowallet.io. For further support requests, please direct them to our support email at support@brainblocks.io as this repo is not checked on a regular basis.
