### ISSUE TITLE
Unpocketed Transaction. How to fix?

### ISSUE THREAD

**Issue by mmodeman** [brainblocks/brainblocks#84]
I sent some NANO from Binance to my Ledger on 2/10/18. Total amount was 28.56. I am now trying to send them back to Binance. But the transaction appears to be stuck because the original transfer is still waiting for a published receive block from Binance. Here is what it looks like on the NANODE.
https://www.nanode.co/block/0D90EA44CB8B1D974039D4DABFA21B0A76FAD3B86E36376B6193BA5353AF0655
I contacted Binance and they told me it was a pro
![Screen Shot 2019-08-14 at 8 27 03 PM](https://user-images.githubusercontent.com/54159238/63134547-e7b6e200-bf97-11e9-8d89-57ad9e883d99.png)
blem with the wallet.  I am getting desperate for my funds.  Can you please assist?  What needs to be done to complete this transaction?  Thank you

Matt Macek

**Comment by schenkty** [comment]
Hey Matt, going to close this as we have resolved it in the support ticket. Please direct all future support issues to our support email at support@brainblocks.io. Thank you!
